### ISSUE TITLE
Minor bug in the quine demo

### ISSUE THREAD

**Issue by codelings-net** [binji/raw-wasm#2]
You're copying 32-bit chunks = 4 bytes at a time, but your source is 0x4a bytes long, which isn't divisible by 4. So your last copy operation includes 2 bytes past the end (which by that time are set to the first two bytes of the source, i.e. 0x00 0x61).

You can see the bug by e.g. setting the length of the array you display in index.html to 0xb0:

data = new Uint8Array(memory.buffer, 0, 0xb0);

**Comment by binji** [comment]
Nice catch, thanks for mentioning! Fixed here: https://github.com/binji/raw-wasm/commit/56da294650de5e307c404abf10a232be65df8bf8.
