### ISSUE TITLE
MIT license missing copyright notice

### ISSUE THREAD

**Issue by MichalStrehovsky** [binji/raw-wasm#3]
These are really nice examples of how WASM works! Would it be possible to add a copyright notice to the LICENSE file so that it's possible to create compliant derived works?

https://opensource.org/licenses/MIT

(The LICENSE file is missing the first line `Copyright <YEAR> <COPYRIGHT HOLDER>` that the rest of LICENSE refers to. Without the copyright line it's not actually possible to comply with the license.)

**Comment by binji** [comment]
Oops, sorry about that. Fixed in 566f04cf7a963323f0dcbcb272207225e408adca.
