### ISSUE TITLE
Wasm `inflate` fails in some cases

### ISSUE THREAD

**Issue by lahmatiy** [binji/raw-wasm#4]
First of all, thank you for such amazing wasm implementation of `inflate`. That's inspiring!

I'm testing wasm version of `inflate` by passing a result of `deflateRawSync` that way:

```js
const { deflateRawSync } = require('zlib');

const compressed = deflateRawSync(Buffer.from('hello worl'.repeat(10)));
```

It works like a charm until number of the string repetition is below 27, i.e. `'hello worl'.repeat(26)` works, but `'hello worl'.repeat(27)` doesn't (returns a corrupted output).

I also tested `inf6502.js` with the same inputs and it works correctly. So that's a wasm version issue only. I suppose the bug is related to fixed huffman tree construction and some kind of overflow.

**Comment by binji** [comment]
Thanks for the report and the simple repro! I figured there must be some bugs here, but I didn't look too hard 😅

**Comment by binji** [comment]
Should be fixed in 57c2eb2eb71eaf38ce4964a2d12211aa3ea19946, let me know if you see any other issues!

**Comment by lahmatiy** [comment]
Wow, that's was quick!
Confirm, 57c2eb2eb71eaf38ce4964a2d12211aa3ea19946 seems to have fixed the issue.
Thank you so much! 🙏

**Comment by binji** [comment]
No problem! Just curious, are you planning to use this somewhere?

**Comment by lahmatiy** [comment]
@binji Yes, I used it in [Discovery.js](https://github.com/discoveryjs/discovery) project (in its [CLI tool](https://github.com/discoveryjs/discovery-cli/releases/tag/v2.3.0)) for an inflating data embedded into HTML page. The project is a tool to build reports/dashboards, and one of its features is to build a report/dashboard as a single static HTML file. The size of data is often dozens and hundreds of megabytes of JSON. A deflating of such size JSON data makes sense, even it requires base64 encoding to embed it into the HTML. According to my measures, the resulting HTML file is reducing 4-10 times (and even more in some cases, depends on JSON structure). So the transfer/download of a HTML page is much faster, offsetting the cost of base64 decoding and subsequent inflate. As a result, overall loading time of a report/dashboard is approximately the same (in case of fast network & server, +/- ~10% difference, depends on JSON structure), but less bytes to transfer (good for slow networks or slow server, in that case overall loading time is much lower) and less memory to keep HTML in memory.

I've compared wasm implementation with [pako](https://github.com/nodeca/pako/), and it gives 2-3 times improvement over pako. However, pako `inflate` implementation is ~10 times bigger in bytes (which is critical for us). Altogether wasm inflate + base64 decoder (inlined into source and base64 encoded) + JS wrapper (which init wasm module synchronously) takes 2760 bytes.

You can find modified version of your inflate implementation with a list of changes [here](https://github.com/discoveryjs/discovery-cli/blob/master/lib/static/inflate/inflate.wat).

Thank you for such a cool project! That's helped me a lot 🙏  And it proved to me that wasm can be handwritten (that's was my first experience with wasm).

**Comment by binji** [comment]
Wow, super cool to see that this was useful in a real product!

I will warn you that there are no safety checks at all in this code, so it would be very easy to have it explode with corrupt (or malicious) data. That said, it should only corrupt the Wasm memory itself, so if you're careful (e.g. don't reuse the Wasm memory on subsequent inflate calls) I think you can detect the corruption and isolate the error from the rest of the app.
